INSERT INTO AUTHORS(NAME) VALUES ('Some Author');
INSERT INTO GENRES(NAME) VALUES ('Some Genre 1');
INSERT INTO GENRES(NAME) VALUES ('Some Genre 2');


INSERT INTO BOOKS(NAME, AUTHOR_ID) VALUES ('Some Book', 1);
INSERT INTO BOOKS_GENRES(BOOK_ID, GENRE_ID) VALUES (1, 1);


