spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54321/db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
  application:
    name: library

management:
  endpoints:
    web:
      exposure:
        include: '*'


#logging:
#  level:
#    ROOT: ERROR
